//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rogue.MetroFire.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rogue.MetroFire.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;hash&quot;:{
        ///        &quot;unicode&quot;:&quot;0023-20E3&quot;,
        ///        &quot;unicode_alternates&quot;:[
        ///            &quot;0023-FE0F-20E3&quot;
        ///        ],
        ///        &quot;name&quot;:&quot;number sign&quot;,
        ///        &quot;shortname&quot;:&quot;:hash:&quot;,
        ///        &quot;category&quot;:&quot;other&quot;,
        ///        &quot;category_order&quot;:&quot;1&quot;,
        ///        &quot;aliases&quot;:[
        ///
        ///        ],
        ///        &quot;aliases_ascii&quot;:[
        ///
        ///        ],
        ///        &quot;keywords&quot;:[
        ///            &quot;symbol&quot;
        ///        ]
        ///    },
        ///    &quot;zero&quot;:{
        ///        &quot;unicode&quot;:&quot;0030-20E3&quot;,
        ///        &quot;unicode_alternates&quot;:[
        ///            &quot;0030-FE0F-20E3&quot;
        ///        ],
        ///        &quot;name&quot;:&quot;digit zero&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string emoji {
            get {
                return ResourceManager.GetString("emoji", resourceCulture);
            }
        }
    }
}
