//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.SampleMainViewModel
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class SampleMainViewModel { }
#else

	public class SampleMainViewModel : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public SampleMainViewModel()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/MetroFire;component/SampleData/SampleMainViewModel/SampleMainViewModel.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private CurrentModules _CurrentModules = new CurrentModules();

		public CurrentModules CurrentModules
		{
			get
			{
				return this._CurrentModules;
			}
		}
	}

	public class CurrentModules : System.Collections.ObjectModel.ObservableCollection<CurrentModulesItem>
	{ 
	}

	public class CurrentModulesItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Caption = string.Empty;

		public string Caption
		{
			get
			{
				return this._Caption;
			}

			set
			{
				if (this._Caption != value)
				{
					this._Caption = value;
					this.OnPropertyChanged("Caption");
				}
			}
		}

		private bool _IsSelected = false;

		public bool IsSelected
		{
			get
			{
				return this._IsSelected;
			}

			set
			{
				if (this._IsSelected != value)
				{
					this._IsSelected = value;
					this.OnPropertyChanged("IsSelected");
				}
			}
		}

		private string _Notifications = string.Empty;

		public string Notifications
		{
			get
			{
				return this._Notifications;
			}

			set
			{
				if (this._Notifications != value)
				{
					this._Notifications = value;
					this.OnPropertyChanged("Notifications");
				}
			}
		}

		private bool _Closable = false;

		public bool Closable
		{
			get
			{
				return this._Closable;
			}

			set
			{
				if (this._Closable != value)
				{
					this._Closable = value;
					this.OnPropertyChanged("Closable");
				}
			}
		}
	}
#endif
}
