// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MetroFire.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Receiving chat room messages")]
    public partial class ReceivingChatRoomMessagesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "DisplayingChatRoomMessages.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Receiving chat room messages", "In order to see messages from others\r\nAs a CampFire user\r\nI want to see the messa" +
                    "ges from others", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("that I am logged in");
#line 8
 testRunner.And("a room called \"Test\"");
#line 9
 testRunner.And("a user \'Testuser\'");
#line 10
 testRunner.And("that I have joined the room \"Test\"");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Receive a single message")]
        public virtual void ReceiveASingleMessage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Receive a single message", ((string[])(null)));
#line 13
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Message"});
            table1.AddRow(new string[] {
                        "1",
                        "Hello world"});
#line 14
 testRunner.When("the following messages are received from user \'Testuser\' for room \"Test\" in order" +
                    ":", ((string)(null)), table1);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Message"});
            table2.AddRow(new string[] {
                        "1",
                        "<Testuser> Hello world"});
#line 17
 testRunner.Then("the following messages should be displayed in room \"Test\" in order:", ((string)(null)), table2);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Receive multiple messages")]
        public virtual void ReceiveMultipleMessages()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Receive multiple messages", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Message"});
            table3.AddRow(new string[] {
                        "1",
                        "Ohai"});
            table3.AddRow(new string[] {
                        "2",
                        "Hai"});
            table3.AddRow(new string[] {
                        "3",
                        "Test"});
#line 22
 testRunner.When("the following messages are received from user \'Testuser\' for room \"Test\" in order" +
                    ":", ((string)(null)), table3);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Message"});
            table4.AddRow(new string[] {
                        "1",
                        "<Testuser> Ohai"});
            table4.AddRow(new string[] {
                        "2",
                        "<Testuser> Hai"});
            table4.AddRow(new string[] {
                        "3",
                        "<Testuser> Test"});
#line 27
 testRunner.Then("the following messages should be displayed in room \"Test\" in order:", ((string)(null)), table4);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Receive multiple messages multiple times")]
        public virtual void ReceiveMultipleMessagesMultipleTimes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Receive multiple messages multiple times", ((string[])(null)));
#line 33
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Message"});
            table5.AddRow(new string[] {
                        "1",
                        "Ohai"});
            table5.AddRow(new string[] {
                        "2",
                        "Hai"});
            table5.AddRow(new string[] {
                        "3",
                        "Test"});
#line 34
 testRunner.When("the following messages are received from user \'Testuser\' for room \"Test\" in order" +
                    ":", ((string)(null)), table5);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Message"});
            table6.AddRow(new string[] {
                        "4",
                        "Blah"});
            table6.AddRow(new string[] {
                        "5",
                        "Nah"});
            table6.AddRow(new string[] {
                        "6",
                        "Zah"});
#line 39
 testRunner.And("the following messages are received from user \'Testuser\' for room \"Test\" in order" +
                    ":", ((string)(null)), table6);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Message"});
            table7.AddRow(new string[] {
                        "<Testuser> Ohai"});
            table7.AddRow(new string[] {
                        "<Testuser> Hai"});
            table7.AddRow(new string[] {
                        "<Testuser> Test"});
            table7.AddRow(new string[] {
                        "<Testuser> Blah"});
            table7.AddRow(new string[] {
                        "<Testuser> Nah"});
            table7.AddRow(new string[] {
                        "<Testuser> Zah"});
#line 44
 testRunner.Then("the following messages should be displayed in room \"Test\" in order:", ((string)(null)), table7);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Show disconnections")]
        [NUnit.Framework.CategoryAttribute("backgroundtestscheduler")]
        public virtual void ShowDisconnections()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Show disconnections", new string[] {
                        "backgroundtestscheduler"});
#line 54
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 55
 testRunner.When("the streaming is disconnected for room \"Test\"");
#line 56
 testRunner.Then("room \"Test\" should show that it is disconnected");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Show reconnections")]
        [NUnit.Framework.CategoryAttribute("backgroundtestscheduler")]
        public virtual void ShowReconnections()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Show reconnections", new string[] {
                        "backgroundtestscheduler"});
#line 59
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 60
 testRunner.When("the streaming is disconnected for room \"Test\"");
#line 61
 testRunner.And("the streaming is reconnected for room \"Test\"");
#line 62
 testRunner.Then("room \"Test\" should show that it is connected");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retrieve old messages when disconnected")]
        [NUnit.Framework.CategoryAttribute("backgroundtestscheduler")]
        public virtual void RetrieveOldMessagesWhenDisconnected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve old messages when disconnected", new string[] {
                        "backgroundtestscheduler"});
#line 65
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 66
 testRunner.When("the streaming is disconnected for room \"Test\"");
#line 67
 testRunner.And("the streaming is reconnected for room \"Test\"");
#line 68
 testRunner.And("we wait 20 seconds");
#line 69
 testRunner.Then("older messages should have been requested for room \"Test\"");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Show old messages sent while disconnected")]
        public virtual void ShowOldMessagesSentWhileDisconnected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Show old messages sent while disconnected", ((string[])(null)));
#line 71
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Message"});
            table8.AddRow(new string[] {
                        "1",
                        "One"});
            table8.AddRow(new string[] {
                        "2",
                        "Two"});
            table8.AddRow(new string[] {
                        "3",
                        "Three"});
#line 72
 testRunner.Given("that the following messages are received from user \'Testuser\' for room \"Test\" in " +
                    "order:", ((string)(null)), table8);
#line 77
 testRunner.When("the streaming is disconnected for room \"Test\"");
#line 78
 testRunner.And("the streaming is reconnected for room \"Test\"");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Message"});
            table9.AddRow(new string[] {
                        "6",
                        "Six"});
            table9.AddRow(new string[] {
                        "7",
                        "Seven"});
#line 79
 testRunner.And("the following messages are received from user \'Testuser\' for room \"Test\" in order" +
                    ":", ((string)(null)), table9);
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Message"});
            table10.AddRow(new string[] {
                        "1",
                        "One"});
            table10.AddRow(new string[] {
                        "2",
                        "Two"});
            table10.AddRow(new string[] {
                        "3",
                        "Three"});
            table10.AddRow(new string[] {
                        "4",
                        "Four"});
            table10.AddRow(new string[] {
                        "5",
                        "Five"});
            table10.AddRow(new string[] {
                        "6",
                        "Six"});
            table10.AddRow(new string[] {
                        "7",
                        "Seven"});
#line 83
 testRunner.And("the following messages are received from user \'Testuser\' for room \"Test\" in order" +
                    ":", ((string)(null)), table10);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Message"});
            table11.AddRow(new string[] {
                        "1",
                        "<Testuser> One"});
            table11.AddRow(new string[] {
                        "2",
                        "<Testuser> Two"});
            table11.AddRow(new string[] {
                        "3",
                        "<Testuser> Three"});
            table11.AddRow(new string[] {
                        "4",
                        "<Testuser> Four"});
            table11.AddRow(new string[] {
                        "5",
                        "<Testuser> Five"});
            table11.AddRow(new string[] {
                        "6",
                        "<Testuser> Six"});
            table11.AddRow(new string[] {
                        "7",
                        "<Testuser> Seven"});
#line 92
 testRunner.Then("the following messages should be displayed in room \"Test\" in order:", ((string)(null)), table11);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Change topic")]
        public virtual void ChangeTopic()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Change topic", ((string[])(null)));
#line 102
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 103
 testRunner.When("the topic is changed to \"To pic\" for room \"Test\"");
#line 104
 testRunner.Then("the topic should be \"To pic\" for room \"Test\"");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
