// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MetroFire.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Login")]
    public partial class LoginFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Login.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Login", "In order to get access to Campfire rooms\r\nAs a Campfire user\r\nI want to enter my " +
                    "account information", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Invalid account name")]
        [NUnit.Framework.CategoryAttribute("backgroundtestscheduler")]
        public virtual void InvalidAccountName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid account name", new string[] {
                        "backgroundtestscheduler"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("that \'Fobsd\' is not a valid Campfire account name");
#line 9
 testRunner.When("I enter \'Fobsd\' for the account name on the login screen");
#line 10
 testRunner.And("I wait 3 seconds");
#line 11
 testRunner.Then("an error message should be displayed on the login screen");
#line 12
 testRunner.And("the account name should not be verified on the login screen");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Valid account name")]
        [NUnit.Framework.CategoryAttribute("backgroundtestscheduler")]
        public virtual void ValidAccountName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Valid account name", new string[] {
                        "backgroundtestscheduler"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
 testRunner.Given("that \'Foobar\' is a valid Campfire account name");
#line 17
 testRunner.When("I enter \'Foobar\' for the account name on the login screen");
#line 18
 testRunner.And("I wait 3 seconds");
#line 19
 testRunner.Then("an error message should not be displayed on the login screen");
#line 20
 testRunner.And("the account name should be verified on the login screen");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
